projects:
  app:
    schemaPath: api/src/schema.graphql
    includes: ["**/*.graphql"]
    extensions:
      endpoints:
        default: http://localhost:4000/api
        subscription: ws://localhost:4000/subscriptions
  database:
    schemaPath: api/src/generated/prisma.graphql
    includes: ["**/*.graphql"]
    extensions:
      prisma: api/database/prisma.yml
      codegen:
        - generator: prisma-binding
          language: typescript
          output:
            binding: api/src/generated/prisma.ts
