# --- web ---
# --- Base Container ---
FROM mhart/alpine-node:10 AS base
WORKDIR /usr/src
# Copy all sources except `packages/api` (seperate dockerfile)
COPY . ./
RUN apk add --no-cache make gcc g++ python
RUN yarn --frozen-lockfile --no-cache
RUN yarn build:web

# --- Install dependencies for production ---
FROM base AS production-dependencies
RUN yarn --frozen-lockfile --no-cache --production 

# --- Release for production ---
FROM mhart/alpine-node:base-10 AS release
WORKDIR /usr/src
COPY --from=base /usr/src/packages/web/build ./web/build
COPY --from=production-dependencies /usr/src/node_modules ./node_modules
COPY --from=production-dependencies /usr/src/packages/web/node_modules ./web/node_modules
ENV NODE_ENV="production"
ENV DEBUG="*,-babel*,-eslint*,-express:*,-compression*"
ENV NOW_CONFIG=./now.web.json
EXPOSE 3000
CMD ["node", "./web/build/server.js"]
