projects:
  app:
    schemaPath: src/schema.graphql
    includes: ["**/*.graphql"]
    extensions:
      endpoints:
        default: http://localhost:4000/graphql
        subscription: ws://localhost:4000/subscriptions
  database:
    schemaPath: src/generated/prisma.graphql
    includes: ["**/*.graphql"]
    extensions:
      prisma: database/prisma.yml
      codegen:
        - generator: prisma-binding
          language: typescript
          output:
            binding: src/generated/prisma.ts
