// flow-typed signature: 62c2c811d55d16519e52fcb6aa006423
// flow-typed version: <<STUB>>/express-async-errors_v2.1.2/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-async-errors'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-async-errors' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-async-errors/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-async-errors/index' {
  declare module.exports: $Exports<'express-async-errors'>;
}
declare module 'express-async-errors/index.js' {
  declare module.exports: $Exports<'express-async-errors'>;
}
declare module 'express-async-errors/test.js' {
  declare module.exports: $Exports<'express-async-errors/test'>;
}
