// flow-typed signature: a9a492afd403d9810ec60b965b45c6c7
// flow-typed version: <<STUB>>/hpp_v0.2.2/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hpp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hpp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hpp/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hpp/lib/index.js' {
  declare module.exports: $Exports<'hpp/lib/index'>;
}
