version: 2
jobs:
  build-dependencies:
    docker:
      - image: circleci/node:10
    working_directory: ~/gamma
    environment:
      CI: false
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v3-dependency-cache-{{ .Branch }}
            - v3-dependency-cache
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: v3-dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/gamma
            - ~/.cache
            # - node_modules
            # - packages/web/node_modules
            # - packages/api/node_modules
            # - packages/shared/node_modules
            # - packages/gamma-core/node_modules
            # - packages/babel-preset-gamma/node_modules
      - run:
          name: Build 'api'
          command: yarn build:api
      - run:
          name: Build 'web'
          command: CI=false yarn build:web
      - save_cache:
          key: v3-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/gamma
            - ~/.cache

  build-prod:
    docker:
      - image: circleci/node:10
    working_directory: ~/gamma
    environment:
      CI: false
    steps:
      - restore_cache:
          key: v3-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Build api
          command: yarn build:api
      - run:
          name: Build web
          command: yarn build:web
      - save_cache:
          key: v3-prod-build-cache-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ./web
            - ./api
            - ./shared

  lint:
    docker:
      - image: circleci/node:10
    working_directory: ~/gamma
    steps:
      - restore_cache:
          key: v3-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Lint
          command: yarn lint

  test-e2e:
    docker:
      - image: circleci/node:10
      - image: cypress/base:8
        environment:
          TERM: xterm
    working_directory: ~/gamma
    steps:
      - restore_cache:
          key: v3-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Start e2e-tests
          command: test $CYPRESS_RECORD_KEY && yarn run test:e2e -- --record || yarn run test:e2e
          background: false
      - save_cache:
          key: v3-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/.cache
      - store_test_results:
          path: results
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
      - store_artifacts:
          path: test-e2e/tests/__image_snapshots__/__diff_output__
          destination: image_snapshot_diff

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-dependencies
      - test-e2e:
          requires:
            - build-dependencies
      - lint:
          requires:
            - build-dependencies
      - build-prod:
          requires:
            - build-dependencies
      - create-docker-image:
          requires:
            - build-prod
            - lint
            - test-e2e
