version: 2
jobs:
  build-dependencies:
    docker:
      - image: circleci/node:10
    working_directory: ~/gamma
    environment:
      CI: false
    steps:
      - checkout
      - restore_cache:
          keys:
            - v5-dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v5-dependency-cache-{{ .Branch }}
            - v5-dependency-cache
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: v5-dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/gamma
            - ~/.cache
      - run:
          name: Build 'api'
          command: yarn build:api
      - run:
          name: Build 'web'
          command: CI=false yarn build:web
      - save_cache:
          key: v5-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/gamma
            - ~/.cache
      - persist_to_workspace:
          root: ~/
          paths:
            - gamma
            - .cache/Cypress

  lint:
    docker:
      - image: circleci/node:10
    working_directory: ~/gamma
    steps:
      - restore_cache:
          key: v5-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Lint
          command: yarn lint

  test-e2e:
    docker:
      - image: cypress/base:8
        environment:
          TERM: xterm
    working_directory: ~/gamma
    steps:
      - attach_workspace:
          at: ~/
      - restore_cache:
          keys:
            - v5-dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v5-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Verify Cypress is installed
          command: yarn cy:verify
      - save_cache:
          key: v5-dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache
      - run:
          name: Start e2e-tests
          # workaround for 'is-ci-cli' issue with env variable `CI=false`
          command: yarn cy:run || yarn run test:e2e
          background: false
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots

  build-prod:
    docker:
      - image: circleci/node:10
    working_directory: ~/gamma
    environment:
      CI: false
    steps:
      - restore_cache:
          key: v5-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Build api
          command: yarn build:api
      - run:
          name: Build web
          command: yarn build:web
      - save_cache:
          key: v5-prod-build-cache-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ./web
            - ./api
            - ./shared

  create-docker-image:
    machine: true
    working_directory: ~/gamma
    steps:
      - checkout
      - restore_cache:
          key: v5-prod-build-cache-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Parameterize ENV variables
          command: |
            echo 'export API_TAG=${CIRCLE_SHA1:0:7}' >> $BASH_ENV
            echo 'export WEB_TAG=${CIRCLE_SHA1:0:7}' >> $BASH_ENV
            echo 'export API_IMAGE=api' >> $BASH_ENV 
            echo 'export WEB_IMAGE=web' >> $BASH_ENV
      - run:
          name: Docker Sign In
          command: |
            echo $DOCKER_PWD | docker login -u $DOCKER_USER --password-stdin
      - run:
          name: Create web image
          command: |
            docker build -t gammaprod/${WEB_IMAGE}:${WEB_TAG} -f "Dockerfile" .
      - run:
          name: Create api image
          working_directory: ~/gamma/packages/api
          command: |
            docker build -t gammaprod/${API_IMAGE}:${API_TAG} -f "Dockerfile" .
      - deploy:
          name: Push web image
          command: |
            docker push gammaprod/${WEB_IMAGE}:${WEB_TAG}
      - deploy:
          name: Push api image
          command: |
            docker push gammaprod/${API_IMAGE}:${API_TAG}

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-dependencies
      - lint:
          requires:
            - build-dependencies
      - test-e2e:
          requires:
            - build-dependencies
            - lint
      - build-prod:
          requires:
            - build-dependencies
            - lint
      - create-docker-image:
          requires:
            - build-prod
            - lint
            - test-e2e
          filters:
            branches:
              only: master
